name: Build React Native Android App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Android APK
    runs-on: self-hosted

    env:
      ORG_GRADLE_JVMARGS: -Xmx4g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          cache: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: android

      - name: Clean Gradle
        run: ./gradlew clean
        working-directory: android

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 1
